quit_simulator = 0
while quit_simulator != "q":
    import random
    print("This is a dice rolling program")
    print("Press Enter to roll")
    input()
    number = random.randint(1,6)
    if number == 1:
        print("[-----------]")
        print("[           ]")
        print("[     0     ]")
        print("[           ]")
        print("[-----------]")
        print()
        print("Type q to quit")
        quit_simulator == input()
    if number == 2:
        print("[-----------]")
        print("[           ]")
        print("[   0   0   ]")
        print("[           ]")
        print("[-----------]")
        print("Type q to quit")
        quit_simulator == input()
    if number == 3:
        print("[-----------]")
        print("[   0   0   ]")
        print("[     0     ]")
        print("[           ]")
        print("[-----------]")
        print("Type q to quit")
        quit_simulator == input()
    if number == 4:
        print("[-----------]")
        print("[   0   0   ]")
        print("[           ]")
        print("[   0   0   ]")
        print("[-----------]")
        print("Type q to quit")
        quit_simulator == input()
    if number == 5:
        print("[-----------]")
        print("[   0   0   ]")
        print("[     0     ]")
        print("[   0   0   ]")
        print("[-----------]")
        print("Type q to quit")
        quit_simulator == input()
    if number == 6:
        print("[-----------]")
        print("[  0    0   ]")
        print("[  0    0   ]")
        print("[  0    0   ]")
        print("[-----------]")
        print("Type q to quit")
        quit_simulator == input()
