print ('Hello World!')
print('What is your name?')
myName = input()
print('it is good to meet you, ' + myName)
print('The length of your name is: ' + str(len(myName)))
print('What is your age?')
myAge = input()
print('you will be ' + str(int(myAge) + 1) + ' Y.O in a year.')
